openapi: 3.0.1
info:
  title: The Platform Custom Component Public API
  version: "1"
servers:
- url: /api/platform/v1
tags:
- description: The Platform Custom Component Public API
  name: custom-component
paths:
  /custom-components/deploy:
    post:
      description: Deploy a new custom component.
      operationId: deployCustomComponent
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/deployCustomComponent_request"
        required: true
      responses:
        "204":
          description: Successful operation.
      summary: Deploy a new custom component
      tags:
      - custom-component
      x-content-type: multipart/form-data
      x-accepts:
      - application/json
components:
  schemas:
    deployCustomComponent_request:
      properties:
        componentFile:
          description: The file of a custom component.
          format: binary
          type: string
      type: object

