/* tslint:disable */
/* eslint-disable */
/**
 * The Automation API Platform Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiCollectionEndpointModel } from './ApiCollectionEndpointModel';
import {
    ApiCollectionEndpointModelFromJSON,
    ApiCollectionEndpointModelFromJSONTyped,
    ApiCollectionEndpointModelToJSON,
} from './ApiCollectionEndpointModel';
import type { TagModel } from './TagModel';
import {
    TagModelFromJSON,
    TagModelFromJSONTyped,
    TagModelToJSON,
} from './TagModel';

/**
 * An API collection.
 * @export
 * @interface ApiCollectionModel
 */
export interface ApiCollectionModel {
    /**
     * The created by.
     * @type {string}
     * @memberof ApiCollectionModel
     */
    readonly createdBy?: string;
    /**
     * The created date.
     * @type {Date}
     * @memberof ApiCollectionModel
     */
    readonly createdDate?: Date;
    /**
     * The description of an API collection.
     * @type {string}
     * @memberof ApiCollectionModel
     */
    description?: string;
    /**
     * If an API collection is enabled or not.
     * @type {boolean}
     * @memberof ApiCollectionModel
     */
    enabled: boolean;
    /**
     * 
     * @type {Array<ApiCollectionEndpointModel>}
     * @memberof ApiCollectionModel
     */
    endpoints?: Array<ApiCollectionEndpointModel>;
    /**
     * The id of an API collection.
     * @type {number}
     * @memberof ApiCollectionModel
     */
    readonly id?: number;
    /**
     * The name of an API collection.
     * @type {string}
     * @memberof ApiCollectionModel
     */
    name: string;
    /**
     * The last modified by.
     * @type {string}
     * @memberof ApiCollectionModel
     */
    readonly lastModifiedBy?: string;
    /**
     * The last modified date.
     * @type {Date}
     * @memberof ApiCollectionModel
     */
    readonly lastModifiedDate?: Date;
    /**
     * The id of a project the API collection is connected to.
     * @type {number}
     * @memberof ApiCollectionModel
     */
    projectId: number;
    /**
     * The id of an project instance the API collection is connected to.
     * @type {number}
     * @memberof ApiCollectionModel
     */
    projectInstanceId?: number;
    /**
     * The version of a project the API collection is connected to.
     * @type {number}
     * @memberof ApiCollectionModel
     */
    projectVersion: number;
    /**
     * 
     * @type {Array<TagModel>}
     * @memberof ApiCollectionModel
     */
    tags?: Array<TagModel>;
    /**
     * The workspace id.
     * @type {number}
     * @memberof ApiCollectionModel
     */
    workspaceId: number;
    /**
     * 
     * @type {number}
     * @memberof ApiCollectionModel
     */
    version?: number;
}

/**
 * Check if a given object implements the ApiCollectionModel interface.
 */
export function instanceOfApiCollectionModel(value: object): boolean {
    if (!('enabled' in value)) return false;
    if (!('name' in value)) return false;
    if (!('projectId' in value)) return false;
    if (!('projectVersion' in value)) return false;
    if (!('workspaceId' in value)) return false;
    return true;
}

export function ApiCollectionModelFromJSON(json: any): ApiCollectionModel {
    return ApiCollectionModelFromJSONTyped(json, false);
}

export function ApiCollectionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiCollectionModel {
    if (json == null) {
        return json;
    }
    return {
        
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
        'description': json['description'] == null ? undefined : json['description'],
        'enabled': json['enabled'],
        'endpoints': json['endpoints'] == null ? undefined : ((json['endpoints'] as Array<any>).map(ApiCollectionEndpointModelFromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'lastModifiedBy': json['lastModifiedBy'] == null ? undefined : json['lastModifiedBy'],
        'lastModifiedDate': json['lastModifiedDate'] == null ? undefined : (new Date(json['lastModifiedDate'])),
        'projectId': json['projectId'],
        'projectInstanceId': json['projectInstanceId'] == null ? undefined : json['projectInstanceId'],
        'projectVersion': json['projectVersion'],
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(TagModelFromJSON)),
        'workspaceId': json['workspaceId'],
        'version': json['__version'] == null ? undefined : json['__version'],
    };
}

export function ApiCollectionModelToJSON(value?: Omit<ApiCollectionModel, 'createdBy'|'createdDate'|'id'|'lastModifiedBy'|'lastModifiedDate'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'enabled': value['enabled'],
        'endpoints': value['endpoints'] == null ? undefined : ((value['endpoints'] as Array<any>).map(ApiCollectionEndpointModelToJSON)),
        'name': value['name'],
        'projectId': value['projectId'],
        'projectInstanceId': value['projectInstanceId'],
        'projectVersion': value['projectVersion'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(TagModelToJSON)),
        'workspaceId': value['workspaceId'],
        '__version': value['version'],
    };
}

