/* tslint:disable */
/* eslint-disable */
/**
 * The Embedded Public V1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AutomationWorkflowProjectWorkflowTemplate } from './AutomationWorkflowProjectWorkflowTemplate';
import {
    AutomationWorkflowProjectWorkflowTemplateFromJSON,
    AutomationWorkflowProjectWorkflowTemplateFromJSONTyped,
    AutomationWorkflowProjectWorkflowTemplateToJSON,
    AutomationWorkflowProjectWorkflowTemplateToJSONTyped,
} from './AutomationWorkflowProjectWorkflowTemplate';

/**
 * An automation workflow catalog project.
 * @export
 * @interface AutomationWorkflowProject
 */
export interface AutomationWorkflowProject {
    /**
     * The id of the automation workflow project.
     */
    id?: number;
    /**
     * The name of the automation workflow project.
     */
    name?: string;
    /**
     * The description of the automation workflow project.
     */
    description?: string;
    /**
     * The list of catalog workflow templates belonging to this project.
     */
    workflowTemplates?: Array<AutomationWorkflowProjectWorkflowTemplate>;
    /**
     * Whether copying this project's templates creates a per-user copy or a shared reference.
     */
    kind?: AutomationWorkflowProjectKindEnum;
}


/**
 * @export
 */
export const AutomationWorkflowProjectKindEnum = {
    Copy: 'COPY',
    Reference: 'REFERENCE',
} as const;
export type AutomationWorkflowProjectKindEnum = typeof AutomationWorkflowProjectKindEnum[keyof typeof AutomationWorkflowProjectKindEnum];


/**
 * Check if a given object implements the AutomationWorkflowProject interface.
 */
export function instanceOfAutomationWorkflowProject(value: object): value is AutomationWorkflowProject {
    return true;
}

export function AutomationWorkflowProjectFromJSON(json: any): AutomationWorkflowProject {
    return AutomationWorkflowProjectFromJSONTyped(json, false);
}

export function AutomationWorkflowProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutomationWorkflowProject {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'workflowTemplates': json['workflowTemplates'] == null ? undefined : ((json['workflowTemplates'] as Array<any>).map(AutomationWorkflowProjectWorkflowTemplateFromJSON)),
        'kind': json['kind'] == null ? undefined : json['kind'],
    };
}

export function AutomationWorkflowProjectToJSON(json: any): AutomationWorkflowProject {
    return AutomationWorkflowProjectToJSONTyped(json, false);
}

export function AutomationWorkflowProjectToJSONTyped(value?: AutomationWorkflowProject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'workflowTemplates': value['workflowTemplates'] == null ? undefined : ((value['workflowTemplates'] as Array<any>).map(AutomationWorkflowProjectWorkflowTemplateToJSON)),
        'kind': value['kind'],
    };
}

