/* tslint:disable */
/* eslint-disable */
/**
 * The Embedded Public V1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A catalog workflow template within an automation workflow project.
 * @export
 * @interface AutomationProjectCodeWorkflowTemplate
 */
export interface AutomationProjectCodeWorkflowTemplate {
    /**
     * The label of the workflow.
     * @type {string}
     * @memberof AutomationProjectCodeWorkflowTemplate
     */
    label?: string;
}

/**
 * Check if a given object implements the AutomationProjectCodeWorkflowTemplate interface.
 */
export function instanceOfAutomationProjectCodeWorkflowTemplate(value: object): value is AutomationProjectCodeWorkflowTemplate {
    return true;
}

export function AutomationProjectCodeWorkflowTemplateFromJSON(json: any): AutomationProjectCodeWorkflowTemplate {
    return AutomationProjectCodeWorkflowTemplateFromJSONTyped(json, false);
}

export function AutomationProjectCodeWorkflowTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutomationProjectCodeWorkflowTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'] == null ? undefined : json['label'],
    };
}

export function AutomationProjectCodeWorkflowTemplateToJSON(json: any): AutomationProjectCodeWorkflowTemplate {
    return AutomationProjectCodeWorkflowTemplateToJSONTyped(json, false);
}

export function AutomationProjectCodeWorkflowTemplateToJSONTyped(value?: AutomationProjectCodeWorkflowTemplate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
    };
}

