/* tslint:disable */
/* eslint-disable */
/**
 * The Embedded Public V1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AutomationProjectCodeWorkflowDeployResult
 */
export interface AutomationProjectCodeWorkflowDeployResult {
    /**
     * 
     * @type {Array<string>}
     * @memberof AutomationProjectCodeWorkflowDeployResult
     */
    warnings?: Array<string>;
}

/**
 * Check if a given object implements the AutomationProjectCodeWorkflowDeployResult interface.
 */
export function instanceOfAutomationProjectCodeWorkflowDeployResult(value: object): value is AutomationProjectCodeWorkflowDeployResult {
    return true;
}

export function AutomationProjectCodeWorkflowDeployResultFromJSON(json: any): AutomationProjectCodeWorkflowDeployResult {
    return AutomationProjectCodeWorkflowDeployResultFromJSONTyped(json, false);
}

export function AutomationProjectCodeWorkflowDeployResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutomationProjectCodeWorkflowDeployResult {
    if (json == null) {
        return json;
    }
    return {
        
        'warnings': json['warnings'] == null ? undefined : json['warnings'],
    };
}

export function AutomationProjectCodeWorkflowDeployResultToJSON(json: any): AutomationProjectCodeWorkflowDeployResult {
    return AutomationProjectCodeWorkflowDeployResultToJSONTyped(json, false);
}

export function AutomationProjectCodeWorkflowDeployResultToJSONTyped(value?: AutomationProjectCodeWorkflowDeployResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'warnings': value['warnings'],
    };
}

