/* tslint:disable */
/* eslint-disable */
/**
 * The Embedded Public V1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AutomationProjectCodeWorkflowTemplate } from './AutomationProjectCodeWorkflowTemplate';
import {
    AutomationProjectCodeWorkflowTemplateFromJSON,
    AutomationProjectCodeWorkflowTemplateFromJSONTyped,
    AutomationProjectCodeWorkflowTemplateToJSON,
    AutomationProjectCodeWorkflowTemplateToJSONTyped,
} from './AutomationProjectCodeWorkflowTemplate';

/**
 * An automation workflow catalog project, without the underlying automation project id.
 * @export
 * @interface AutomationProjectCodeWorkflow
 */
export interface AutomationProjectCodeWorkflow {
    /**
     * The name of the automation workflow project.
     */
    name?: string;
    /**
     * Whether copying this project's templates creates a per-user copy or a shared reference.
     */
    kind?: AutomationProjectCodeWorkflowKindEnum;
    /**
     * The list of catalog workflow templates belonging to this project.
     */
    workflowTemplates?: Array<AutomationProjectCodeWorkflowTemplate>;
}


/**
 * @export
 */
export const AutomationProjectCodeWorkflowKindEnum = {
    Copy: 'COPY',
    Reference: 'REFERENCE',
} as const;
export type AutomationProjectCodeWorkflowKindEnum = typeof AutomationProjectCodeWorkflowKindEnum[keyof typeof AutomationProjectCodeWorkflowKindEnum];


/**
 * Check if a given object implements the AutomationProjectCodeWorkflow interface.
 */
export function instanceOfAutomationProjectCodeWorkflow(value: object): value is AutomationProjectCodeWorkflow {
    return true;
}

export function AutomationProjectCodeWorkflowFromJSON(json: any): AutomationProjectCodeWorkflow {
    return AutomationProjectCodeWorkflowFromJSONTyped(json, false);
}

export function AutomationProjectCodeWorkflowFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutomationProjectCodeWorkflow {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'workflowTemplates': json['workflowTemplates'] == null ? undefined : ((json['workflowTemplates'] as Array<any>).map(AutomationProjectCodeWorkflowTemplateFromJSON)),
    };
}

export function AutomationProjectCodeWorkflowToJSON(json: any): AutomationProjectCodeWorkflow {
    return AutomationProjectCodeWorkflowToJSONTyped(json, false);
}

export function AutomationProjectCodeWorkflowToJSONTyped(value?: AutomationProjectCodeWorkflow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'kind': value['kind'],
        'workflowTemplates': value['workflowTemplates'] == null ? undefined : ((value['workflowTemplates'] as Array<any>).map(AutomationProjectCodeWorkflowTemplateToJSON)),
    };
}

