/* tslint:disable */
/* eslint-disable */
/**
 * The Embedded Public V1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Returned when a code workflow template is copied; code workflow templates can only be referenced.
 * @export
 * @interface CodeWorkflowNotCopyableError
 */
export interface CodeWorkflowNotCopyableError {
    /**
     * 
     */
    reason?: CodeWorkflowNotCopyableErrorReasonEnum;
}


/**
 * @export
 */
export const CodeWorkflowNotCopyableErrorReasonEnum = {
    CodeWorkflowNotCopyable: 'CODE_WORKFLOW_NOT_COPYABLE',
} as const;
export type CodeWorkflowNotCopyableErrorReasonEnum = typeof CodeWorkflowNotCopyableErrorReasonEnum[keyof typeof CodeWorkflowNotCopyableErrorReasonEnum];


/**
 * Check if a given object implements the CodeWorkflowNotCopyableError interface.
 */
export function instanceOfCodeWorkflowNotCopyableError(value: object): value is CodeWorkflowNotCopyableError {
    return true;
}

export function CodeWorkflowNotCopyableErrorFromJSON(json: any): CodeWorkflowNotCopyableError {
    return CodeWorkflowNotCopyableErrorFromJSONTyped(json, false);
}

export function CodeWorkflowNotCopyableErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeWorkflowNotCopyableError {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function CodeWorkflowNotCopyableErrorToJSON(json: any): CodeWorkflowNotCopyableError {
    return CodeWorkflowNotCopyableErrorToJSONTyped(json, false);
}

export function CodeWorkflowNotCopyableErrorToJSONTyped(value?: CodeWorkflowNotCopyableError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
    };
}

