/* tslint:disable */
/* eslint-disable */
/**
 * The Embedded Public V1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { Environment } from './Environment';
import {
    EnvironmentFromJSON,
    EnvironmentFromJSONTyped,
    EnvironmentToJSON,
    EnvironmentToJSONTyped,
} from './Environment';

/**
 * Contains all required information to open a connection to a service defined by componentName parameter
 * @export
 * @interface Connection
 */
export interface Connection {
    /**
     * The id of an integration.
     */
    id: number;
    /**
     * The name of a connection.
     */
    name: string;
    /**
     * 
     */
    environment?: Environment;
    /**
     * The component name.
     */
    componentName?: string;
    /**
     * The connection version.
     */
    connectionVersion?: number;
    /**
     * The authorization type name.
     */
    authorizationType?: string;
    /**
     * The created date.
     */
    createdDate?: Date;
    /**
     * Whether a tenant admin marked this connection shared with every connected user in the environment. Shared and owned are independent: a connected user may own a connection the admin also shared, and can still modify that one -- see `editable`.
     */
    shared?: boolean;
    /**
     * Whether THIS connected user may reconnect or delete the connection, which is true only of the ones they own. A shared connection they do not own is listed and selectable but never modifiable: it belongs to the tenant admin who shared it, and changing it would act on every connected user at once.
     */
    editable?: boolean;
}



/**
 * Check if a given object implements the Connection interface.
 */
export function instanceOfConnection(value: object): value is Connection {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ConnectionFromJSON(json: any): Connection {
    return ConnectionFromJSONTyped(json, false);
}

export function ConnectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Connection {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'environment': json['environment'] == null ? undefined : EnvironmentFromJSON(json['environment']),
        'componentName': json['componentName'] == null ? undefined : json['componentName'],
        'connectionVersion': json['connectionVersion'] == null ? undefined : json['connectionVersion'],
        'authorizationType': json['authorizationType'] == null ? undefined : json['authorizationType'],
        'createdDate': json['createdDate'] == null ? undefined : (parseDateTime(json['createdDate'])),
        'shared': json['shared'] == null ? undefined : json['shared'],
        'editable': json['editable'] == null ? undefined : json['editable'],
    };
}

export function ConnectionToJSON(json: any): Connection {
    return ConnectionToJSONTyped(json, false);
}

export function ConnectionToJSONTyped(value?: Connection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'environment': EnvironmentToJSON(value['environment']),
        'componentName': value['componentName'],
        'connectionVersion': value['connectionVersion'],
        'authorizationType': value['authorizationType'],
        'createdDate': value['createdDate'] == null ? value['createdDate'] : serializeDateTime(value['createdDate']),
        'shared': value['shared'],
        'editable': value['editable'],
    };
}

