/* tslint:disable */
/* eslint-disable */
/**
 * The Embedded Public V1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { AutomationWorkflowProjectWorkflowInput } from './AutomationWorkflowProjectWorkflowInput';
import {
    AutomationWorkflowProjectWorkflowInputFromJSON,
    AutomationWorkflowProjectWorkflowInputFromJSONTyped,
    AutomationWorkflowProjectWorkflowInputToJSON,
    AutomationWorkflowProjectWorkflowInputToJSONTyped,
} from './AutomationWorkflowProjectWorkflowInput';
import type { AutomationWorkflowProjectComponent } from './AutomationWorkflowProjectComponent';
import {
    AutomationWorkflowProjectComponentFromJSON,
    AutomationWorkflowProjectComponentFromJSONTyped,
    AutomationWorkflowProjectComponentToJSON,
    AutomationWorkflowProjectComponentToJSONTyped,
} from './AutomationWorkflowProjectComponent';

/**
 * A group of tasks that make one logical workflow.
 * @export
 * @interface ConnectedUserProjectWorkflow
 */
export interface ConnectedUserProjectWorkflow {
    /**
     * The created date of a workflow.
     */
    createdDate?: Date;
    /**
     * The description of a workflow.
     */
    description?: string;
    /**
     * The definition of a workflow.
     */
    definition?: string;
    /**
     * The last modified date of a workflow.
     */
    lastModifiedDate?: Date;
    /**
     * If a workflow is enabled or not.
     */
    enabled?: boolean;
    /**
     * The label of a workflow.
     */
    label?: string;
    /**
     * The reference code of a workflow.
     */
    workflowUuid?: string;
    /**
     * The workflow version, if null a workflow is not yet published
     */
    workflowVersion?: number;
    /**
     * COPY when the workflow is the user's own editable copy; REFERENCE when it points at a shared catalog workflow.
     */
    kind?: ConnectedUserProjectWorkflowKindEnum;
    /**
     * For REFERENCE rows, the uuid of the catalog workflow being referenced.
     */
    catalogWorkflowUuid?: string;
    /**
     * For COPY rows, the uuid of the catalog template the copy was created from. Null otherwise.
     */
    copiedFromWorkflowUuid?: string;
    /**
     * True when a REFERENCE points at a catalog workflow that is no longer served.
     */
    dangling?: boolean;
    /**
     * The components used by the workflow.
     */
    components?: Array<AutomationWorkflowProjectComponent>;
    /**
     * The values the connected user is asked for before this workflow runs.
     */
    inputs?: Array<AutomationWorkflowProjectWorkflowInput>;
    /**
     * The values the connected user has already supplied, keyed by input name.
     */
    inputValues?: { [key: string]: any; };
    /**
     * Why a REFERENCE needs attention: MISSING_CONNECTION:<component>, INPUT_REQUIRED:<input> or UPDATE_PENDING. Null when healthy or for COPY rows.
     */
    attentionReason?: string;
}


/**
 * @export
 */
export const ConnectedUserProjectWorkflowKindEnum = {
    Copy: 'COPY',
    Reference: 'REFERENCE',
} as const;
export type ConnectedUserProjectWorkflowKindEnum = typeof ConnectedUserProjectWorkflowKindEnum[keyof typeof ConnectedUserProjectWorkflowKindEnum];


/**
 * Check if a given object implements the ConnectedUserProjectWorkflow interface.
 */
export function instanceOfConnectedUserProjectWorkflow(value: object): value is ConnectedUserProjectWorkflow {
    return true;
}

export function ConnectedUserProjectWorkflowFromJSON(json: any): ConnectedUserProjectWorkflow {
    return ConnectedUserProjectWorkflowFromJSONTyped(json, false);
}

export function ConnectedUserProjectWorkflowFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectedUserProjectWorkflow {
    if (json == null) {
        return json;
    }
    return {
        
        'createdDate': json['createdDate'] == null ? undefined : (parseDateTime(json['createdDate'])),
        'description': json['description'] == null ? undefined : json['description'],
        'definition': json['definition'] == null ? undefined : json['definition'],
        'lastModifiedDate': json['lastModifiedDate'] == null ? undefined : (parseDateTime(json['lastModifiedDate'])),
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'label': json['label'] == null ? undefined : json['label'],
        'workflowUuid': json['workflowUuid'] == null ? undefined : json['workflowUuid'],
        'workflowVersion': json['workflowVersion'] == null ? undefined : json['workflowVersion'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'catalogWorkflowUuid': json['catalogWorkflowUuid'] == null ? undefined : json['catalogWorkflowUuid'],
        'copiedFromWorkflowUuid': json['copiedFromWorkflowUuid'] == null ? undefined : json['copiedFromWorkflowUuid'],
        'dangling': json['dangling'] == null ? undefined : json['dangling'],
        'components': json['components'] == null ? undefined : ((json['components'] as Array<any>).map(AutomationWorkflowProjectComponentFromJSON)),
        'inputs': json['inputs'] == null ? undefined : ((json['inputs'] as Array<any>).map(AutomationWorkflowProjectWorkflowInputFromJSON)),
        'inputValues': json['inputValues'] == null ? undefined : json['inputValues'],
        'attentionReason': json['attentionReason'] == null ? undefined : json['attentionReason'],
    };
}

export function ConnectedUserProjectWorkflowToJSON(json: any): ConnectedUserProjectWorkflow {
    return ConnectedUserProjectWorkflowToJSONTyped(json, false);
}

export function ConnectedUserProjectWorkflowToJSONTyped(value?: ConnectedUserProjectWorkflow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdDate': value['createdDate'] == null ? value['createdDate'] : serializeDateTime(value['createdDate']),
        'description': value['description'],
        'definition': value['definition'],
        'lastModifiedDate': value['lastModifiedDate'] == null ? value['lastModifiedDate'] : serializeDateTime(value['lastModifiedDate']),
        'enabled': value['enabled'],
        'label': value['label'],
        'workflowUuid': value['workflowUuid'],
        'workflowVersion': value['workflowVersion'],
        'kind': value['kind'],
        'catalogWorkflowUuid': value['catalogWorkflowUuid'],
        'copiedFromWorkflowUuid': value['copiedFromWorkflowUuid'],
        'dangling': value['dangling'],
        'components': value['components'] == null ? undefined : ((value['components'] as Array<any>).map(AutomationWorkflowProjectComponentToJSON)),
        'inputs': value['inputs'] == null ? undefined : ((value['inputs'] as Array<any>).map(AutomationWorkflowProjectWorkflowInputToJSON)),
        'inputValues': value['inputValues'],
        'attentionReason': value['attentionReason'],
    };
}

