/* tslint:disable */
/* eslint-disable */
/**
 * The Embedded Public V1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IntegrationInstance } from './IntegrationInstance';
import {
    IntegrationInstanceFromJSON,
    IntegrationInstanceFromJSONTyped,
    IntegrationInstanceToJSON,
    IntegrationInstanceToJSONTyped,
} from './IntegrationInstance';
import type { McpTool } from './McpTool';
import {
    McpToolFromJSON,
    McpToolFromJSONTyped,
    McpToolToJSON,
    McpToolToJSONTyped,
} from './McpTool';
import type { ConnectionConfig } from './ConnectionConfig';
import {
    ConnectionConfigFromJSON,
    ConnectionConfigFromJSONTyped,
    ConnectionConfigToJSON,
    ConnectionConfigToJSONTyped,
} from './ConnectionConfig';
import type { IntegrationWorkflow } from './IntegrationWorkflow';
import {
    IntegrationWorkflowFromJSON,
    IntegrationWorkflowFromJSONTyped,
    IntegrationWorkflowToJSON,
    IntegrationWorkflowToJSONTyped,
} from './IntegrationWorkflow';

/**
 * A group of workflows that make one logical integration for a particular service represented by component.
 * @export
 * @interface Integration
 */
export interface Integration {
    /**
     * The name of the integration's component.
     */
    componentName: string;
    /**
     * The description of a project.
     */
    description?: string;
    /**
     * The icon.
     */
    icon: string;
    /**
     * The id of an integration.
     */
    id?: number;
    /**
     * The list of integration instances that represent configured and connected integrations for specific users
     */
    integrationInstances?: Array<IntegrationInstance>;
    /**
     * The version of an integration.
     */
    integrationVersion?: number;
    /**
     * If multiple instances of an integration are allowed or not.
     */
    multipleInstances: boolean;
    /**
     * The name of an integration.
     */
    name?: string;
    /**
     * 
     */
    connectionConfig?: ConnectionConfig;
    /**
     * The list of MCP workflows defined for this integration.
     */
    readonly mcpWorkflows?: Array<IntegrationWorkflow>;
    /**
     * The list of MCP tools defined for this integration's component.
     */
    readonly mcpTools?: Array<McpTool>;
    /**
     * The list of workflows.
     */
    workflows?: Array<IntegrationWorkflow>;
}

/**
 * Check if a given object implements the Integration interface.
 */
export function instanceOfIntegration(value: object): value is Integration {
    if (!('componentName' in value) || value['componentName'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('multipleInstances' in value) || value['multipleInstances'] === undefined) return false;
    return true;
}

export function IntegrationFromJSON(json: any): Integration {
    return IntegrationFromJSONTyped(json, false);
}

export function IntegrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Integration {
    if (json == null) {
        return json;
    }
    return {
        
        'componentName': json['componentName'],
        'description': json['description'] == null ? undefined : json['description'],
        'icon': json['icon'],
        'id': json['id'] == null ? undefined : json['id'],
        'integrationInstances': json['integrationInstances'] == null ? undefined : ((json['integrationInstances'] as Array<any>).map(IntegrationInstanceFromJSON)),
        'integrationVersion': json['integrationVersion'] == null ? undefined : json['integrationVersion'],
        'multipleInstances': json['multipleInstances'],
        'name': json['name'] == null ? undefined : json['name'],
        'connectionConfig': json['connectionConfig'] == null ? undefined : ConnectionConfigFromJSON(json['connectionConfig']),
        'mcpWorkflows': json['mcpWorkflows'] == null ? undefined : ((json['mcpWorkflows'] as Array<any>).map(IntegrationWorkflowFromJSON)),
        'mcpTools': json['mcpTools'] == null ? undefined : ((json['mcpTools'] as Array<any>).map(McpToolFromJSON)),
        'workflows': json['workflows'] == null ? undefined : ((json['workflows'] as Array<any>).map(IntegrationWorkflowFromJSON)),
    };
}

export function IntegrationToJSON(json: any): Integration {
    return IntegrationToJSONTyped(json, false);
}

export function IntegrationToJSONTyped(value?: Omit<Integration, 'mcpWorkflows'|'mcpTools'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'componentName': value['componentName'],
        'description': value['description'],
        'icon': value['icon'],
        'id': value['id'],
        'integrationInstances': value['integrationInstances'] == null ? undefined : ((value['integrationInstances'] as Array<any>).map(IntegrationInstanceToJSON)),
        'integrationVersion': value['integrationVersion'],
        'multipleInstances': value['multipleInstances'],
        'name': value['name'],
        'connectionConfig': ConnectionConfigToJSON(value['connectionConfig']),
        'workflows': value['workflows'] == null ? undefined : ((value['workflows'] as Array<any>).map(IntegrationWorkflowToJSON)),
    };
}

