/* tslint:disable */
/* eslint-disable */
/**
 * The Embedded Public V1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IntegrationInstance } from './IntegrationInstance';
import {
    IntegrationInstanceFromJSON,
    IntegrationInstanceFromJSONTyped,
    IntegrationInstanceToJSON,
    IntegrationInstanceToJSONTyped,
} from './IntegrationInstance';

/**
 * A group of workflows that make one logical integration for a particular service represented by component.
 * @export
 * @interface IntegrationBasic
 */
export interface IntegrationBasic {
    /**
     * The name of the integration's component.
     */
    componentName: string;
    /**
     * The description of a project.
     */
    description?: string;
    /**
     * The icon.
     */
    icon: string;
    /**
     * The id of an integration.
     */
    id?: number;
    /**
     * The list of integration instances that represent configured and connected integrations for specific users
     */
    integrationInstances?: Array<IntegrationInstance>;
    /**
     * The version of an integration.
     */
    integrationVersion?: number;
    /**
     * If multiple instances of an integration are allowed or not.
     */
    multipleInstances: boolean;
    /**
     * The name of an integration.
     */
    name?: string;
}

/**
 * Check if a given object implements the IntegrationBasic interface.
 */
export function instanceOfIntegrationBasic(value: object): value is IntegrationBasic {
    if (!('componentName' in value) || value['componentName'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('multipleInstances' in value) || value['multipleInstances'] === undefined) return false;
    return true;
}

export function IntegrationBasicFromJSON(json: any): IntegrationBasic {
    return IntegrationBasicFromJSONTyped(json, false);
}

export function IntegrationBasicFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationBasic {
    if (json == null) {
        return json;
    }
    return {
        
        'componentName': json['componentName'],
        'description': json['description'] == null ? undefined : json['description'],
        'icon': json['icon'],
        'id': json['id'] == null ? undefined : json['id'],
        'integrationInstances': json['integrationInstances'] == null ? undefined : ((json['integrationInstances'] as Array<any>).map(IntegrationInstanceFromJSON)),
        'integrationVersion': json['integrationVersion'] == null ? undefined : json['integrationVersion'],
        'multipleInstances': json['multipleInstances'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function IntegrationBasicToJSON(json: any): IntegrationBasic {
    return IntegrationBasicToJSONTyped(json, false);
}

export function IntegrationBasicToJSONTyped(value?: IntegrationBasic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'componentName': value['componentName'],
        'description': value['description'],
        'icon': value['icon'],
        'id': value['id'],
        'integrationInstances': value['integrationInstances'] == null ? undefined : ((value['integrationInstances'] as Array<any>).map(IntegrationInstanceToJSON)),
        'integrationVersion': value['integrationVersion'],
        'multipleInstances': value['multipleInstances'],
        'name': value['name'],
    };
}

