/* tslint:disable */
/* eslint-disable */
/**
 * The Embedded Public V1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Connections the connected user chose, keyed by component name. Components not listed keep their current connection or are auto-matched.
 * @export
 * @interface ProvisionWorkflowReferenceRequest
 */
export interface ProvisionWorkflowReferenceRequest {
    /**
     * 
     */
    connections?: { [key: string]: number; };
}

/**
 * Check if a given object implements the ProvisionWorkflowReferenceRequest interface.
 */
export function instanceOfProvisionWorkflowReferenceRequest(value: object): value is ProvisionWorkflowReferenceRequest {
    return true;
}

export function ProvisionWorkflowReferenceRequestFromJSON(json: any): ProvisionWorkflowReferenceRequest {
    return ProvisionWorkflowReferenceRequestFromJSONTyped(json, false);
}

export function ProvisionWorkflowReferenceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProvisionWorkflowReferenceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'connections': json['connections'] == null ? undefined : json['connections'],
    };
}

export function ProvisionWorkflowReferenceRequestToJSON(json: any): ProvisionWorkflowReferenceRequest {
    return ProvisionWorkflowReferenceRequestToJSONTyped(json, false);
}

export function ProvisionWorkflowReferenceRequestToJSONTyped(value?: ProvisionWorkflowReferenceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connections': value['connections'],
    };
}

