/* tslint:disable */
/* eslint-disable */
/**
 * The Embedded Public V1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AutomationProjectCodeWorkflow,
    AutomationProjectCodeWorkflowFromJSON,
    AutomationProjectCodeWorkflowToJSON,
} from '../models/AutomationProjectCodeWorkflow';
import {
    type AutomationProjectCodeWorkflowDeployResult,
    AutomationProjectCodeWorkflowDeployResultFromJSON,
    AutomationProjectCodeWorkflowDeployResultToJSON,
} from '../models/AutomationProjectCodeWorkflowDeployResult';

export interface DeployAutomationProjectCodeWorkflowRequest {
    projectFile?: Blob;
}

/**
 * 
 */
export class AutomationProjectCodeWorkflowApi extends runtime.BaseAPI {

    /**
     * Creates request options for deployAutomationProjectCodeWorkflow without sending the request
     */
    async deployAutomationProjectCodeWorkflowRequestOpts(requestParameters: DeployAutomationProjectCodeWorkflowRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['projectFile'] != null) {
            formParams.append('projectFile', requestParameters['projectFile'] as any);
        }


        let urlPath = `/automation-project-code-workflows/deploy`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Deploy a new automation code workflow into the embedded catalog. Unlike the connected-user-scoped endpoints on this API, this operation is authenticated as the API key\'s own ByteChef user and does not fabricate a connected-user identity.
     * Deploy a new automation code workflow into the embedded catalog
     */
    async deployAutomationProjectCodeWorkflowRaw(requestParameters: DeployAutomationProjectCodeWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AutomationProjectCodeWorkflowDeployResult>> {
        const requestOptions = await this.deployAutomationProjectCodeWorkflowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AutomationProjectCodeWorkflowDeployResultFromJSON(jsonValue));
    }

    /**
     * Deploy a new automation code workflow into the embedded catalog. Unlike the connected-user-scoped endpoints on this API, this operation is authenticated as the API key\'s own ByteChef user and does not fabricate a connected-user identity.
     * Deploy a new automation code workflow into the embedded catalog
     */
    async deployAutomationProjectCodeWorkflow(requestParameters: DeployAutomationProjectCodeWorkflowRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AutomationProjectCodeWorkflowDeployResult> {
        const response = await this.deployAutomationProjectCodeWorkflowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAutomationProjectCodeWorkflows without sending the request
     */
    async listAutomationProjectCodeWorkflowsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/automation-project-code-workflows`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List catalog projects in the embedded automation bridge. Unlike the connected-user-scoped endpoints on this API, this operation is authenticated as the API key\'s own ByteChef user and does not fabricate a connected-user identity.
     * List catalog projects in the embedded automation bridge
     */
    async listAutomationProjectCodeWorkflowsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AutomationProjectCodeWorkflow>>> {
        const requestOptions = await this.listAutomationProjectCodeWorkflowsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AutomationProjectCodeWorkflowFromJSON));
    }

    /**
     * List catalog projects in the embedded automation bridge. Unlike the connected-user-scoped endpoints on this API, this operation is authenticated as the API key\'s own ByteChef user and does not fabricate a connected-user identity.
     * List catalog projects in the embedded automation bridge
     */
    async listAutomationProjectCodeWorkflows(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AutomationProjectCodeWorkflow>> {
        const response = await this.listAutomationProjectCodeWorkflowsRaw(initOverrides);
        return await response.value();
    }

}
