query dataSyncs($workspaceId: ID!) {
    dataSyncs(workspaceId: $workspaceId) {
        id
        name
        title
        description
        projectId
        triggerType
        triggerParameters
        elements {
            id
            kind
            componentName
            componentVersion
            operationName
        }
        tags {
            id
            name
        }
        unpublishedChanges
        lastPublishedVersion
        publishedDate
        lastModifiedDate
        visibility
    }
}
