/* tslint:disable */
/* eslint-disable */
/**
 * The Embedded Configuration Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';

export interface DeployIntegrationRequest {
    integrationFile?: Blob;
}

/**
 * 
 */
export class IntegrationCodeWorkflowApi extends runtime.BaseAPI {

    /**
     * Creates request options for deployIntegration without sending the request
     */
    async deployIntegrationRequestOpts(requestParameters: DeployIntegrationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['integrationFile'] != null) {
            formParams.append('integrationFile', requestParameters['integrationFile'] as any);
        }


        let urlPath = `/integrations/deploy`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Deploy a new code based integration.
     * Deploy a new code based integration
     */
    async deployIntegrationRaw(requestParameters: DeployIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deployIntegrationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deploy a new code based integration.
     * Deploy a new code based integration
     */
    async deployIntegration(requestParameters: DeployIntegrationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deployIntegrationRaw(requestParameters, initOverrides);
    }

}
