/* tslint:disable */
/* eslint-disable */
/**
 * The Platform Custom Component Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An custom component.
 * @export
 * @interface CustomComponentModel
 */
export interface CustomComponentModel {
    /**
     * The version of a custom component.
     * @type {number}
     * @memberof CustomComponentModel
     */
    componentVersion?: number;
    /**
     * The created by.
     * @type {string}
     * @memberof CustomComponentModel
     */
    readonly createdBy?: string;
    /**
     * The created date.
     * @type {Date}
     * @memberof CustomComponentModel
     */
    readonly createdDate?: Date;
    /**
     * The description of a custom component.
     * @type {string}
     * @memberof CustomComponentModel
     */
    description?: string;
    /**
     * If a custom component is enabled or not.
     * @type {boolean}
     * @memberof CustomComponentModel
     */
    enabled?: boolean;
    /**
     * The icon of a custom component.
     * @type {string}
     * @memberof CustomComponentModel
     */
    icon?: string;
    /**
     * The id of an custom component.
     * @type {number}
     * @memberof CustomComponentModel
     */
    id?: number;
    /**
     * The language in which the component is implemented
     * @type {string}
     * @memberof CustomComponentModel
     */
    readonly language?: CustomComponentModelLanguageEnum;
    /**
     * The last modified by.
     * @type {string}
     * @memberof CustomComponentModel
     */
    readonly lastModifiedBy?: string;
    /**
     * The last modified date.
     * @type {Date}
     * @memberof CustomComponentModel
     */
    readonly lastModifiedDate?: Date;
    /**
     * The name of a custom component.
     * @type {string}
     * @memberof CustomComponentModel
     */
    name: string;
    /**
     * The title of a custom component.
     * @type {string}
     * @memberof CustomComponentModel
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof CustomComponentModel
     */
    version?: number;
}


/**
 * @export
 */
export const CustomComponentModelLanguageEnum = {
    Java: 'JAVA',
    Javascript: 'JAVASCRIPT',
    Python: 'PYTHON',
    Ruby: 'RUBY'
} as const;
export type CustomComponentModelLanguageEnum = typeof CustomComponentModelLanguageEnum[keyof typeof CustomComponentModelLanguageEnum];


/**
 * Check if a given object implements the CustomComponentModel interface.
 */
export function instanceOfCustomComponentModel(value: object): boolean {
    if (!('name' in value)) return false;
    return true;
}

export function CustomComponentModelFromJSON(json: any): CustomComponentModel {
    return CustomComponentModelFromJSONTyped(json, false);
}

export function CustomComponentModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomComponentModel {
    if (json == null) {
        return json;
    }
    return {
        
        'componentVersion': json['componentVersion'] == null ? undefined : json['componentVersion'],
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
        'description': json['description'] == null ? undefined : json['description'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'id': json['id'] == null ? undefined : json['id'],
        'language': json['language'] == null ? undefined : json['language'],
        'lastModifiedBy': json['lastModifiedBy'] == null ? undefined : json['lastModifiedBy'],
        'lastModifiedDate': json['lastModifiedDate'] == null ? undefined : (new Date(json['lastModifiedDate'])),
        'name': json['name'],
        'title': json['title'] == null ? undefined : json['title'],
        'version': json['__version'] == null ? undefined : json['__version'],
    };
}

export function CustomComponentModelToJSON(value?: Omit<CustomComponentModel, 'createdBy'|'createdDate'|'language'|'lastModifiedBy'|'lastModifiedDate'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'componentVersion': value['componentVersion'],
        'description': value['description'],
        'enabled': value['enabled'],
        'icon': value['icon'],
        'id': value['id'],
        'name': value['name'],
        'title': value['title'],
        '__version': value['version'],
    };
}

