/* tslint:disable */
/* eslint-disable */
/**
 * The Platform API Connector Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HttpMethodModel } from './HttpMethodModel';
import {
    HttpMethodModelFromJSON,
    HttpMethodModelFromJSONTyped,
    HttpMethodModelToJSON,
} from './HttpMethodModel';

/**
 * An API connector.
 * @export
 * @interface ApiConnectorEndpointModel
 */
export interface ApiConnectorEndpointModel {
    /**
     * The created by.
     * @type {string}
     * @memberof ApiConnectorEndpointModel
     */
    readonly createdBy?: string;
    /**
     * The created date.
     * @type {Date}
     * @memberof ApiConnectorEndpointModel
     */
    readonly createdDate?: Date;
    /**
     * The description of an API connector's endpoint.
     * @type {string}
     * @memberof ApiConnectorEndpointModel
     */
    description?: string;
    /**
     * 
     * @type {HttpMethodModel}
     * @memberof ApiConnectorEndpointModel
     */
    httpMethod?: HttpMethodModel;
    /**
     * The id of the API connector's endpoint.
     * @type {number}
     * @memberof ApiConnectorEndpointModel
     */
    id?: number;
    /**
     * The last execution date.
     * @type {Date}
     * @memberof ApiConnectorEndpointModel
     */
    readonly lastExecutionDate?: Date;
    /**
     * The last modified by.
     * @type {string}
     * @memberof ApiConnectorEndpointModel
     */
    readonly lastModifiedBy?: string;
    /**
     * The last modified date.
     * @type {Date}
     * @memberof ApiConnectorEndpointModel
     */
    readonly lastModifiedDate?: Date;
    /**
     * The name of an API connector's endpoint.
     * @type {string}
     * @memberof ApiConnectorEndpointModel
     */
    name: string;
    /**
     * The path of an API connector's endpoint.
     * @type {string}
     * @memberof ApiConnectorEndpointModel
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiConnectorEndpointModel
     */
    version?: number;
}

/**
 * Check if a given object implements the ApiConnectorEndpointModel interface.
 */
export function instanceOfApiConnectorEndpointModel(value: object): boolean {
    if (!('name' in value)) return false;
    return true;
}

export function ApiConnectorEndpointModelFromJSON(json: any): ApiConnectorEndpointModel {
    return ApiConnectorEndpointModelFromJSONTyped(json, false);
}

export function ApiConnectorEndpointModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiConnectorEndpointModel {
    if (json == null) {
        return json;
    }
    return {
        
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
        'description': json['description'] == null ? undefined : json['description'],
        'httpMethod': json['httpMethod'] == null ? undefined : HttpMethodModelFromJSON(json['httpMethod']),
        'id': json['id'] == null ? undefined : json['id'],
        'lastExecutionDate': json['lastExecutionDate'] == null ? undefined : (new Date(json['lastExecutionDate'])),
        'lastModifiedBy': json['lastModifiedBy'] == null ? undefined : json['lastModifiedBy'],
        'lastModifiedDate': json['lastModifiedDate'] == null ? undefined : (new Date(json['lastModifiedDate'])),
        'name': json['name'],
        'path': json['path'] == null ? undefined : json['path'],
        'version': json['__version'] == null ? undefined : json['__version'],
    };
}

export function ApiConnectorEndpointModelToJSON(value?: Omit<ApiConnectorEndpointModel, 'createdBy'|'createdDate'|'lastExecutionDate'|'lastModifiedBy'|'lastModifiedDate'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'httpMethod': HttpMethodModelToJSON(value['httpMethod']),
        'id': value['id'],
        'name': value['name'],
        'path': value['path'],
        '__version': value['version'],
    };
}

