/* tslint:disable */
/* eslint-disable */
/**
 * The Platform API Connector Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiConnectorEndpointModel } from './ApiConnectorEndpointModel';
import {
    ApiConnectorEndpointModelFromJSON,
    ApiConnectorEndpointModelFromJSONTyped,
    ApiConnectorEndpointModelToJSON,
} from './ApiConnectorEndpointModel';
import type { TagModel } from './TagModel';
import {
    TagModelFromJSON,
    TagModelFromJSONTyped,
    TagModelToJSON,
} from './TagModel';

/**
 * An API connector.
 * @export
 * @interface ApiConnectorModel
 */
export interface ApiConnectorModel {
    /**
     * The version of an API connector.
     * @type {string}
     * @memberof ApiConnectorModel
     */
    connectorVersion: string;
    /**
     * The created by.
     * @type {string}
     * @memberof ApiConnectorModel
     */
    readonly createdBy?: string;
    /**
     * The created date.
     * @type {Date}
     * @memberof ApiConnectorModel
     */
    readonly createdDate?: Date;
    /**
     * The description of an API connector.
     * @type {string}
     * @memberof ApiConnectorModel
     */
    description?: string;
    /**
     * The definition of an API connector.
     * @type {string}
     * @memberof ApiConnectorModel
     */
    readonly definition?: string;
    /**
     * If an API connector is enabled or not.
     * @type {boolean}
     * @memberof ApiConnectorModel
     */
    enabled?: boolean;
    /**
     * 
     * @type {Array<ApiConnectorEndpointModel>}
     * @memberof ApiConnectorModel
     */
    endpoints?: Array<ApiConnectorEndpointModel>;
    /**
     * The icon of an API connector.
     * @type {string}
     * @memberof ApiConnectorModel
     */
    icon?: string;
    /**
     * The id of the API connector.
     * @type {number}
     * @memberof ApiConnectorModel
     */
    id?: number;
    /**
     * The last modified by.
     * @type {string}
     * @memberof ApiConnectorModel
     */
    readonly lastModifiedBy?: string;
    /**
     * The last modified date.
     * @type {Date}
     * @memberof ApiConnectorModel
     */
    readonly lastModifiedDate?: Date;
    /**
     * The name of an API connector.
     * @type {string}
     * @memberof ApiConnectorModel
     */
    name: string;
    /**
     * The specification of an API connector.
     * @type {string}
     * @memberof ApiConnectorModel
     */
    readonly specification?: string;
    /**
     * 
     * @type {Array<TagModel>}
     * @memberof ApiConnectorModel
     */
    tags?: Array<TagModel>;
    /**
     * The title of an API connector.
     * @type {string}
     * @memberof ApiConnectorModel
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiConnectorModel
     */
    version?: number;
}

/**
 * Check if a given object implements the ApiConnectorModel interface.
 */
export function instanceOfApiConnectorModel(value: object): boolean {
    if (!('connectorVersion' in value)) return false;
    if (!('name' in value)) return false;
    return true;
}

export function ApiConnectorModelFromJSON(json: any): ApiConnectorModel {
    return ApiConnectorModelFromJSONTyped(json, false);
}

export function ApiConnectorModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiConnectorModel {
    if (json == null) {
        return json;
    }
    return {
        
        'connectorVersion': json['connectorVersion'],
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
        'description': json['description'] == null ? undefined : json['description'],
        'definition': json['definition'] == null ? undefined : json['definition'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'endpoints': json['endpoints'] == null ? undefined : ((json['endpoints'] as Array<any>).map(ApiConnectorEndpointModelFromJSON)),
        'icon': json['icon'] == null ? undefined : json['icon'],
        'id': json['id'] == null ? undefined : json['id'],
        'lastModifiedBy': json['lastModifiedBy'] == null ? undefined : json['lastModifiedBy'],
        'lastModifiedDate': json['lastModifiedDate'] == null ? undefined : (new Date(json['lastModifiedDate'])),
        'name': json['name'],
        'specification': json['specification'] == null ? undefined : json['specification'],
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(TagModelFromJSON)),
        'title': json['title'] == null ? undefined : json['title'],
        'version': json['__version'] == null ? undefined : json['__version'],
    };
}

export function ApiConnectorModelToJSON(value?: Omit<ApiConnectorModel, 'createdBy'|'createdDate'|'definition'|'lastModifiedBy'|'lastModifiedDate'|'specification'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'connectorVersion': value['connectorVersion'],
        'description': value['description'],
        'enabled': value['enabled'],
        'endpoints': value['endpoints'] == null ? undefined : ((value['endpoints'] as Array<any>).map(ApiConnectorEndpointModelToJSON)),
        'icon': value['icon'],
        'id': value['id'],
        'name': value['name'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(TagModelToJSON)),
        'title': value['title'],
        '__version': value['version'],
    };
}

