/* eslint-disable */

import type {ComponentInputReference} from '@/shared/middleware/platform/configuration/models/ComponentInputReference';

// Hand-maintained augmentation of the generated `WorkflowInput` model. The `componentReference` field shadows the
// `Input` schema in
// server/ee/libs/embedded/embedded-configuration/embedded-configuration-public-rest/openapi.yaml — keep it in sync
// with that schema. This is a deliberate subset: the EE configuration dialog only consumes the reference identity
// (componentName/componentVersion/groupName), not the resolved `group` object the SDK uses. The shared
// `ComponentInputReference` type is reused so the EE `Workflow` stays assignable to the automation/platform `Workflow`.
// If the OpenAPI source gains/renames these fields, update this file too (it is not regenerated by codegen).
declare module '@/ee/shared/middleware/embedded/configuration/models/WorkflowInput' {
    interface WorkflowInput {
        componentReference?: ComponentInputReference;
    }
}

export {};
