/* tslint:disable */
/* eslint-disable */
/**
 * The Embedded Configuration Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A unified integration.
 * @export
 * @interface UnifiedIntegrationModel
 */
export interface UnifiedIntegrationModel {
    /**
     * The created by.
     * @type {string}
     * @memberof UnifiedIntegrationModel
     */
    readonly createdBy?: string;
    /**
     * The created date.
     * @type {Date}
     * @memberof UnifiedIntegrationModel
     */
    readonly createdDate?: Date;
    /**
     * The id of a unified integration.
     * @type {number}
     * @memberof UnifiedIntegrationModel
     */
    id?: number;
    /**
     * The name of a unified category.
     * @type {string}
     * @memberof UnifiedIntegrationModel
     */
    categoryName: string;
    /**
     * The name of component with unified API support.
     * @type {string}
     * @memberof UnifiedIntegrationModel
     */
    componentName: string;
    /**
     * The last modified by.
     * @type {string}
     * @memberof UnifiedIntegrationModel
     */
    readonly lastModifiedBy?: string;
    /**
     * The last modified date.
     * @type {Date}
     * @memberof UnifiedIntegrationModel
     */
    readonly lastModifiedDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof UnifiedIntegrationModel
     */
    version?: number;
}

/**
 * Check if a given object implements the UnifiedIntegrationModel interface.
 */
export function instanceOfUnifiedIntegrationModel(value: object): boolean {
    if (!('categoryName' in value)) return false;
    if (!('componentName' in value)) return false;
    return true;
}

export function UnifiedIntegrationModelFromJSON(json: any): UnifiedIntegrationModel {
    return UnifiedIntegrationModelFromJSONTyped(json, false);
}

export function UnifiedIntegrationModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnifiedIntegrationModel {
    if (json == null) {
        return json;
    }
    return {
        
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
        'id': json['id'] == null ? undefined : json['id'],
        'categoryName': json['categoryName'],
        'componentName': json['componentName'],
        'lastModifiedBy': json['lastModifiedBy'] == null ? undefined : json['lastModifiedBy'],
        'lastModifiedDate': json['lastModifiedDate'] == null ? undefined : (new Date(json['lastModifiedDate'])),
        'version': json['__version'] == null ? undefined : json['__version'],
    };
}

export function UnifiedIntegrationModelToJSON(value?: Omit<UnifiedIntegrationModel, 'createdBy'|'createdDate'|'lastModifiedBy'|'lastModifiedDate'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'categoryName': value['categoryName'],
        'componentName': value['componentName'],
        '__version': value['version'],
    };
}

