/*
 * Copyright 2025 ByteChef
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.bytechef.automation.datasync.util;

import com.bytechef.automation.datasync.domain.DataSync;
import com.bytechef.automation.datasync.domain.DataSync.TriggerType;
import com.bytechef.automation.datasync.domain.DataSyncElement;
import com.bytechef.automation.datasync.domain.DataSyncElement.Kind;
import com.bytechef.commons.util.JsonUtils;
import com.bytechef.commons.util.MapUtils;
import com.bytechef.platform.configuration.constant.WorkflowExtConstants;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Renders a {@link DataSync} and its {@link DataSyncElement} rows into one workflow-definition JSON: one trigger
 * ({@code manual/v1/trigger} or {@code schedule/v1/cron}) feeding one {@code dataStream/v1/stream} task whose
 * {@code clusterElements} carry the source, destination and (when present) the field-mapper processor. Node names are
 * fixed so the client can address options, display-condition and test lookups without discovering them.
 *
 * <p>
 * Deterministic: only {@link LinkedHashMap}s, rows read in {@link Kind} order, no clock or random reads — the same
 * discipline as {@code AiAgentWorkflowGenerator} and {@code KnowledgeBaseSourceWorkflowGenerator}.
 *
 * @author Ivica Cardic
 */
public final class DataSyncWorkflowGenerator {

    public static final String TRIGGER_NODE_NAME = "trigger_1";
    public static final String TASK_NODE_NAME = "dataStream_1";
    public static final String METADATA_DATA_SYNC_ID = "dataSyncId";

    public static final String TRIGGER_PARAMETER_EXPRESSION = "expression";
    public static final String TRIGGER_PARAMETER_TIMEZONE = "timezone";

    private static final String MANUAL_TRIGGER_TYPE = "manual/v1/trigger";
    private static final String SCHEDULE_CRON_TRIGGER_TYPE = "schedule/v1/cron";
    private static final String DATA_STREAM_STREAM_TYPE = "dataStream/v1/stream";
    private static final String DEFAULT_TIMEZONE = "UTC";

    private DataSyncWorkflowGenerator() {
    }

    public static String nodeName(Kind kind) {
        return switch (kind) {
            case SOURCE -> "source_1";
            case DESTINATION -> "destination_1";
            case PROCESSOR -> "processor_1";
        };
    }

    public static String generate(DataSync dataSync, List<DataSyncElement> elements) {
        Objects.requireNonNull(dataSync, "dataSync");
        Objects.requireNonNull(elements, "elements");

        Map<String, Object> definition = new LinkedHashMap<>();

        definition.put("label", dataSync.getTitle());
        definition.put("description", "Auto-generated by Data Sync. Edits via the Data Sync UI.");
        definition.put("inputs", List.of());

        Map<String, Object> metadata = new LinkedHashMap<>();

        metadata.put(METADATA_DATA_SYNC_ID, dataSync.getId());

        definition.put("metadata", metadata);
        definition.put("triggers", List.of(buildTrigger(dataSync)));
        definition.put("tasks", List.of(buildTask(dataSync, elements)));

        return JsonUtils.write(definition);
    }

    private static Map<String, Object> buildTrigger(DataSync dataSync) {
        Map<String, Object> trigger = new LinkedHashMap<>();

        trigger.put("name", TRIGGER_NODE_NAME);

        if (dataSync.getTriggerType() == TriggerType.MANUAL) {
            trigger.put("label", "Manual");
            trigger.put("type", MANUAL_TRIGGER_TYPE);
            trigger.put("parameters", new LinkedHashMap<>());

            return trigger;
        }

        Map<String, ?> triggerParameters = dataSync.getTriggerParameters();

        Map<String, Object> parameters = new LinkedHashMap<>();

        parameters.put(
            TRIGGER_PARAMETER_EXPRESSION, MapUtils.getString(triggerParameters, TRIGGER_PARAMETER_EXPRESSION, ""));
        parameters.put(
            TRIGGER_PARAMETER_TIMEZONE,
            MapUtils.getString(triggerParameters, TRIGGER_PARAMETER_TIMEZONE, DEFAULT_TIMEZONE));

        trigger.put("label", "Schedule");
        trigger.put("type", SCHEDULE_CRON_TRIGGER_TYPE);
        trigger.put("parameters", parameters);

        return trigger;
    }

    private static Map<String, Object> buildTask(DataSync dataSync, List<DataSyncElement> elements) {
        Map<String, Object> task = new LinkedHashMap<>();

        task.put("name", TASK_NODE_NAME);
        task.put("label", dataSync.getTitle());
        task.put("type", DATA_STREAM_STREAM_TYPE);
        task.put("parameters", new LinkedHashMap<>());

        Map<String, Object> clusterElements = new LinkedHashMap<>();

        for (Kind kind : Kind.values()) {
            Optional<DataSyncElement> element = elements.stream()
                .filter(candidate -> candidate.getKind() == kind)
                .findFirst();

            // The cluster element map key is ClusterElementType.key(): lowercase source / destination / processor.
            element.ifPresent(dataSyncElement -> clusterElements.put(
                kind.name()
                    .toLowerCase(),
                buildClusterElement(dataSyncElement)));
        }

        task.put("clusterElements", clusterElements);

        return task;
    }

    private static Map<String, Object> buildClusterElement(DataSyncElement element) {
        String nodeName = nodeName(element.getKind());
        String type = element.getType();

        Map<String, Object> clusterElement = new LinkedHashMap<>();

        clusterElement.put("name", nodeName);
        clusterElement.put("label", element.getComponentName());
        clusterElement.put("type", type);
        clusterElement.put("parameters", new LinkedHashMap<>(element.getParameters()));
        clusterElement.put(WorkflowExtConstants.CONNECTIONS, buildConnections(element, nodeName));

        return clusterElement;
    }

    /**
     * Keyed by the element's own node name — the key every runtime consumer and the deployment dialog look the
     * connection up under (see {@code AiAgentWorkflowGenerator#buildClusterElementConnections}).
     */
    private static Map<String, Object> buildConnections(DataSyncElement element, String nodeName) {
        Map<String, Object> connection = new LinkedHashMap<>();

        connection.put(WorkflowExtConstants.COMPONENT_NAME, element.getComponentName());
        connection.put(WorkflowExtConstants.COMPONENT_VERSION, element.getComponentVersion());

        Map<String, Object> connections = new LinkedHashMap<>();

        connections.put(nodeName, connection);

        return connections;
    }
}
