/*
 * Copyright 2025 ByteChef
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.bytechef.automation.configuration.workflow;

import com.bytechef.automation.configuration.domain.ProjectWorkflowType;
import com.bytechef.automation.configuration.service.ProjectWorkflowService;
import com.bytechef.platform.configuration.workflow.WorkflowUpdateGuard;
import org.springframework.stereotype.Component;

/**
 * Refuses direct edits to a workflow generated by another feature's own configuration — an AI agent or a Data Sync —
 * which owns and regenerates it, so an editor write by id would be overwritten on the next generation and can leave the
 * owner and its workflow out of step.
 *
 * @author Ivica Cardic
 */
@Component
public final class GeneratedProjectWorkflowUpdateGuard implements WorkflowUpdateGuard {

    private final ProjectWorkflowService projectWorkflowService;

    GeneratedProjectWorkflowUpdateGuard(ProjectWorkflowService projectWorkflowService) {
        this.projectWorkflowService = projectWorkflowService;
    }

    @Override
    public void checkUpdatable(String workflowId) {
        projectWorkflowService.fetchWorkflowProjectWorkflow(workflowId)
            .filter(projectWorkflow -> projectWorkflow.getType()
                .isGenerated())
            .ifPresent(projectWorkflow -> {
                throw new IllegalArgumentException(generatedWorkflowMessage(workflowId, projectWorkflow.getType()));
            });
    }

    /**
     * The guard's message table: names the feature that owns and regenerates the workflow, keyed on
     * {@link ProjectWorkflowType}. The switch is exhaustive on purpose - a future generated type fails compilation here
     * until it has a message of its own.
     */
    public static String generatedWorkflowMessage(String workflowId, ProjectWorkflowType type) {
        return switch (type) {
            case AI_AGENT -> "Workflow %s is generated by an AI agent; edit it through the agent"
                .formatted(workflowId);
            case DATA_SYNC -> "Workflow %s is generated by a Data Sync; edit it through the Data Sync"
                .formatted(workflowId);
            case WORKFLOW -> throw new IllegalArgumentException("Workflow %s is not generated".formatted(workflowId));
        };
    }
}
