query EmbeddedKnowledgeBases($environmentId: ID!, $ownerId: ID) {
    embeddedKnowledgeBases(environmentId: $environmentId, ownerId: $ownerId) {
        id
        name
        description
        createdDate
        lastModifiedDate
        ownerId
        maxChunkSize
        minChunkSizeChars
        overlap
    }
}

mutation AssignEmbeddedKnowledgeBaseOwner($input: AssignKnowledgeBaseOwnerInput!) {
    assignEmbeddedKnowledgeBaseOwner(input: $input)
}

mutation CreateEmbeddedKnowledgeBase($input: CreateEmbeddedKnowledgeBaseInput!) {
    createEmbeddedKnowledgeBase(input: $input)
}

mutation UpdateEmbeddedKnowledgeBase($input: UpdateEmbeddedKnowledgeBaseInput!) {
    updateEmbeddedKnowledgeBase(input: $input)
}
