/*
 * Copyright 2025 ByteChef
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.bytechef.automation.configuration.workflow;

import static org.assertj.core.api.Assertions.assertThatCode;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.bytechef.automation.configuration.domain.ProjectWorkflow;
import com.bytechef.automation.configuration.domain.ProjectWorkflowType;
import com.bytechef.automation.configuration.service.ProjectWorkflowService;
import java.util.Optional;
import org.junit.jupiter.api.Test;

/**
 * @author Ivica Cardic
 */
class GeneratedProjectWorkflowUpdateGuardTest {

    private final ProjectWorkflowService projectWorkflowService = mock(ProjectWorkflowService.class);
    private final GeneratedProjectWorkflowUpdateGuard generatedProjectWorkflowUpdateGuard =
        new GeneratedProjectWorkflowUpdateGuard(projectWorkflowService);

    @Test
    void testRefusesAiAgentWorkflowNamingTheAgent() {
        when(projectWorkflowService.fetchWorkflowProjectWorkflow("agent-workflow"))
            .thenReturn(Optional.of(new ProjectWorkflow(1L, 1, "agent-workflow", ProjectWorkflowType.AI_AGENT)));

        assertThatThrownBy(() -> generatedProjectWorkflowUpdateGuard.checkUpdatable("agent-workflow"))
            .isInstanceOf(IllegalArgumentException.class)
            .hasMessage("Workflow agent-workflow is generated by an AI agent; edit it through the agent");
    }

    @Test
    void testRefusesDataSyncWorkflowNamingTheDataSync() {
        when(projectWorkflowService.fetchWorkflowProjectWorkflow("data-sync-workflow"))
            .thenReturn(Optional.of(new ProjectWorkflow(1L, 1, "data-sync-workflow", ProjectWorkflowType.DATA_SYNC)));

        assertThatThrownBy(() -> generatedProjectWorkflowUpdateGuard.checkUpdatable("data-sync-workflow"))
            .isInstanceOf(IllegalArgumentException.class)
            .hasMessage("Workflow data-sync-workflow is generated by a Data Sync; edit it through the Data Sync");
    }

    @Test
    void testAllowsOrdinaryWorkflow() {
        when(projectWorkflowService.fetchWorkflowProjectWorkflow("workflow"))
            .thenReturn(Optional.of(new ProjectWorkflow(1L, 1, "workflow", ProjectWorkflowType.WORKFLOW)));

        assertThatCode(() -> generatedProjectWorkflowUpdateGuard.checkUpdatable("workflow"))
            .doesNotThrowAnyException();
    }

    @Test
    void testAllowsUnknownWorkflowId() {
        when(projectWorkflowService.fetchWorkflowProjectWorkflow("integration-workflow"))
            .thenReturn(Optional.empty());

        assertThatCode(() -> generatedProjectWorkflowUpdateGuard.checkUpdatable("integration-workflow"))
            .doesNotThrowAnyException();
    }
}
